name: Format code with black

on:
  push:
    branches:
      - main
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Format code
      run: |
        black .
