name: Test and Lint on Push

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up conda
      uses: actions/setup-conda@v2
      with:
        conda_version: 4.10.11
    - name: Create conda environment
      run: conda env create -f environment.yml
    - name: Activate conda environment
      run: conda activate myenv
    - name: Run pytest
      run: pytest
    - name: Run flake8
      run: flake8 .
