# This workflow is used for Continuous Integration (CI)
# It is triggered by a push to the main or master branch

name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # This step checks out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # This step sets up conda in the runner's environment
    - name: Set up conda
      uses: actions/setup-conda@v2
      
    # This step creates a conda environment using the environment.yml file
    # and activates the environment
    - name: Create conda environment
      run: |
        conda env create -f environment.yml
        echo "conda activate $(head -1 environment.yml | cut -d' ' -f2)" >> ~/.bashrc
        source ~/.bashrc

    # This step installs the black package in the environment
    - name: Install black
      run: |
        conda install black

    # This step runs the black formatter on all the python files in the repository
    # and checks if any files need to be formatted
    - name: Run black
      run: |
        black --check .

    # This step runs the pytest tests
    - name: Run pytest
      run: |
        python -m pytest

    # This step runs the flake8 linter on the code in the repository
    - name: Run flake8
      run: |
        flake8 .
