name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2
    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Run black formatter
    - name: Run black formatter
      run: |
        pip install black
        black .
    # DVC setup and command
    - name: Pull dependencies with DVC
      run: |
        dvc pull
    # AWS set    
    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ env.AWS_REGION }}

    - name: Deploy to AWS
      run: |
        aws s3 sync . ${{ secrets.AWS_BUCKET_NAME_LINK }}        
    # Run flake8 linter
    #- name: Run flake8 linter
    #  run: |
    #    pip install flake8
    #    flake8 .
    # Run pytest
    #- name: Run pytest
    #  run: |
    #    pip install pytest
    #    pytest
